const texts = [
    "The band's back together again. And again. And again.",
    "It's Encore-ing time!",
    "wow it's an encore in here!",
    "If En, then only Core!",
    "Also try YARG!",
    "Also try Rock Band 3 Deluxe!",
    "Also try Clone Hero!",
    "Also try GHWT:DE!",
    "Also try FNLookup!",
    "I hope this grabs your attention!",
    "acai if you see this please dm me \"banana\"!",
    "powered by HTML, css, javascript, and some enby's autism",
    "Trans Rights!",
    "Queer Rights!",
    "we do not discussion that here.",
    "There's a pipe bomb in your mailbox! Better get it! :3",
    "The overshell was the best invention since sliced bread!",
    "No practice mode; it's cheating!",
    "Encore? More like - EnCOOL!😎",
    "Media streaming error!",
    "It's Only Connor was here!",
    "there's no way",
    "open source !",
    "dont ask the chart verifiers to verify charts, they will hunt you down",
    "SPLASHTEXT.JS SPLASHTEXT.JS SPLASHTEXT.JS - TEXT IS QUITE LONG - YES - AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "insert text",
    "that's it, [un-cores your encore.]",
    "[plays game], wow that's cool menu, lets add that to encore",
    "In loving memory of Zwarkledarg... gone too soon!",
    "explaining plurality to an american: so imagine two patties in one burger!",
    "Uncaught SyntaxError: Unexpected string           splashtext.js:32",
    "if u dont fuck with the gays dont play our game",
    "it's so fucked up that nobody knows any other paintings by shakespeare besides the mona lisa!",
    "you lost the game",
    "Encore Missions? no, that's the wrong game!",
    "some kind of encore...",
    "stretching the amount of text this array can have",
    "Grains of Sand is too powerful for Encore.",
    "gay people",
    "lesbian people",
    "foxes",
    "awwruf",
    "mraoww",
    "https://protogen.network",
    "say hi to dave",
    "\"say hi to dave\", that was a command, not a asking you to say something.",
    "back when games were cool...",
    "trans people",
    "ngl i dont actually know javascript",
    "what could this strange device be? when i touch it, it gives forth a sound...",
    "shit, piss, fuck, cunt, cocksucker, motherfucker, tits, fart, turd, and twat",
    "dm the bot.",
    "54",
    "how did we get here ?",
    "if this text appears, something is critially wrong",
    "Got your nose!",
    "funny reference!",
    "multiple instruments!",
    "we are NOT getting a new guitar hero, stop lying",
    "now with added notes!",
    "encore 2, coming soon.",
    "encore core",
    "very magenta"
];

const randomIndex = Math.floor(Math.random() * texts.length);
document.getElementById('splash').innerText = texts[randomIndex];